service: lambda-test

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: hello
         method: get
         integration: lambda
         response:
            headers:
              Content-Type: "'text/html'"
            template: $input.path('$')
         request:
           template:
             application/json: '{ "source_ip" : "$context.identity.sourceIp" }'
